version: "3.8"
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./laravel:/app
    - ./config.json:/docker-entrypoint.d/config.json
    ports:
    - 80:80
    container_name: laravel